// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLcjf9pJLSwCF0zBXq-0-_aYxx8cF7sI',
    appId: '1:829981996033:web:eb586682ec2a4833897c00',
    messagingSenderId: '829981996033',
    projectId: 'nexis-4723a',
    authDomain: 'nexis-4723a.firebaseapp.com',
    storageBucket: 'nexis-4723a.appspot.com',
    measurementId: 'G-8TPZZGGKLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6d3aDt-_FI_b4qxRr577Wny8CfGBNus',
    appId: '1:829981996033:android:e086cad5f81c6aa4897c00',
    messagingSenderId: '829981996033',
    projectId: 'nexis-4723a',
    storageBucket: 'nexis-4723a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD8dGfPtXCjQdzgvZ1dhIahrw2t6lJXGY',
    appId: '1:829981996033:ios:2b8804df0825b125897c00',
    messagingSenderId: '829981996033',
    projectId: 'nexis-4723a',
    storageBucket: 'nexis-4723a.appspot.com',
    iosClientId: '829981996033-njrtk1op43vunpsvan0gd45g5bo2493j.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD8dGfPtXCjQdzgvZ1dhIahrw2t6lJXGY',
    appId: '1:829981996033:ios:2b8804df0825b125897c00',
    messagingSenderId: '829981996033',
    projectId: 'nexis-4723a',
    storageBucket: 'nexis-4723a.appspot.com',
    iosClientId: '829981996033-njrtk1op43vunpsvan0gd45g5bo2493j.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexis',
  );
}
