name: Flutter CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter actions
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # This will use the latest stable version

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./nexis

    - name: Create .env file
      run: |
        echo "FIREBASE_API_KEY=test_value1" > ./nexis/.env
        echo "FIREBASE_PROJECT_ID=test_value2" >> ./nexis/.env
      working-directory: ./nexis

    - name: Run Flutter tests
      run: flutter test
      working-directory: ./nexis